version: "3.3"
services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - "SPRING_PROFILES_ACTIVE=local"
    volumes:
      - ./:/weedbuddy-api
      - ./.m2:/root/.m2
    working_dir: /weedbuddy-api
    command: sh run.sh
    ports:
      - "8080:8080"
      - "5005:5005"

  database:
      image: mysql
